[project]
name = "seras-english-grammar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pdf2image>=1.17.0",
    "pypdf>=6.6.2",
]
